[package]
name = "shellbookmark"
version = "0.1.0"
authors = ["Kai Sickeler <k.sickeler@gmail.com>"]

[dependencies]
clap = "*"
rustbreak = { git = "https://github.com/asuivelentine/rustbreak", branch = "debug" }
regex = "*"
